import './global.css';
import App from './pages/app/app';
import { openProductPage } from './pages/catalog/listeners/openProductPage';
import { getModal } from './pages/catalog/listeners/getModal';
import { paginateModal } from './pages/catalog/listeners/paginateModal';
import { removeModal } from './pages/catalog/listeners/removeModal';
import { tokenFetcher } from './server/accessTokenCC';
import { plusMinusOneProduct } from './pages/catalog/listeners/plusMinusOneProduct';
import { constants } from './data/constants';
import { submitLogin } from './pages/logReg/validation/authorizationFunctions/submitData/submitLogin';
import { submitReg } from './pages/logReg/validation/authorizationFunctions/submitData/submitReg';
import { openCategory } from './pages/catalog/listeners/openCategory';
import { openSubCategories } from './pages/catalog/listeners/openSubCategories';

const app = new App();
app.run();
export const bearer_token_cc: Promise<string> = tokenFetcher.fetchAccessToken();
submitLogin(constants.authorizationObject);
submitReg(constants.regObj);
getModal();
removeModal();
paginateModal();
openProductPage();
plusMinusOneProduct();
openCategory();
openSubCategories();
